-- Primary Key--
-- Tabela "usuarios"

ALTER TABLE IF EXISTS usuarios
ADD PRIMARY KEY (id);

ALTER TABLE IF EXISTS usuarios
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Tabela "destinos"
ALTER TABLE IF EXISTS destinos
ADD PRIMARY KEY (id);

ALTER TABLE IF EXISTS destinos
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Tabela "reservas"
ALTER TABLE IF EXISTS reservas
ADD PRIMARY KEY (id);

ALTER TABLE IF EXISTS reservas
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Exemplos --

-- Inserção na tabela "usuarios"
INSERT INTO usuarios (nome, email, data_nascimento, endereco)
VALUES ('João Maria', 'joaomaria@example.com', '1990-01-01', 'Rua A, 123');

-- Inserção na tabela "destinos"
INSERT INTO destinos (nome, descricao)
VALUES ('Praia Teste', 'Destino paradisíaco com belas praias.');

-- Inserção na tabela "reservas"
INSERT INTO reservas (id_usuario, id_destino, data, status)
VALUES (4, 1, '2023-07-01', 'pendente');

-- Chaves estrangeiras --

-- Adicionando chave estrangeira na tabela "reservas" referenciando a tabela "usuarios"
ALTER TABLE reservas
ADD CONSTRAINT fk_reservas_usuarios
FOREIGN KEY (id_usuario) REFERENCES usuarios(id);

-- Adicionando chave estrangeira na tabela "reservas" referenciando a tabela "destinos"
ALTER TABLE reservas
ADD CONSTRAINT fk_reservas_destinos
FOREIGN KEY (id_destino) REFERENCES destinos(id);

-- Alterando a restrição da chave estrangeira "fk_reservas_usuarios" na tabela "reservas" para ON DELETE CASCADE
ALTER TABLE reservas
DROP CONSTRAINT fk_reservas_usuarios;

ALTER TABLE reservas
ADD CONSTRAINT fk_reservas_usuarios
FOREIGN KEY (id_usuario) REFERENCES usuarios(id)
ON DELETE CASCADE; -- ao ser excluido um usuário também é excluido sua reserva

-- Consultas
SELECT * from usuarios;
SELECT * from destinos;
SELECT * from reservas;

-- Exclusões
DELETE FROM usuarios WHERE id = 2;



